package HTTP;

public enum Endpoint {
    POST_ADD_OR_UPDATE_SIMPLETASK,
    POST_ADD_OR_UPDATE_EPICTASK,
    POST_ADD_OR_UPDATE_SUBTASK,
    GET_SIMPLETASKS,
    GET_EPICTASKS,
    GET_SUBTASKS,
    DELETE_ALL_SIMPLETASKS,
    DELETE_ALL_EPICTASKS,
    DELETE_ALL_SUBTASKS,
    GET_SIMPLETASK_BY_ID,
    GET_EPICTASK_BY_ID,
    GET_SUBTASK_BY_ID,
    DELETE_SIMPLETASK_BY_ID,
    DELETE_EPICTASK_BY_ID,
    DELETE_SUBTASK_BY_ID,
    GET_SUB_OF_EPIC,
    GET_PRIORITIZED_TASK,
    GET_TASK_HISTORY,
    UNKNOWN
}
